"""users table

Revision ID: 271da12663d1
Revises: 91da6cbd488f
Create Date: 2023-12-19 10:12:33.532796

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '271da12663d1'
down_revision = '91da6cbd488f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=256), nullable=True))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', sa.VARCHAR(length=256), nullable=True))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###
